# Generated by Django 4.2 on 2023-04-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artisan',
        ),
    ]
