# Generated by Django 4.2 on 2023-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0003_rename_artisan_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
